function [] = board(n)
%BOARD Create the tic-tac-toe board based on user inputs
%The main function in the game, the board function takes an input used for
%the board_size of the board. the board function declares most of the global
%variables used and sets their initial values. Then depending on the board_size,
%the board function creates the appropriately board_sized board

close all;
%Variable Declarations
global game
global board_size;
global sq11 sq12 sq13 sq14 sq15 sq21 sq22 sq23 sq24 sq25 sq31 sq32 sq33...
    sq34 sq35 sq41 sq42 sq43 sq44 sq45 sq51 sq52 sq53 sq54 sq55;
global settings;
global reset
global turn;
global matrix_board;
global game_over;
global music;
global backgroundmusic;
%Global Variable Instantiations 
game = figure('Name', 'Tic-Tac-Toe','Color','black');
set(game,'Menubar','none','Position',[30 10 700 500]);
ha=axes('units','normalized','position',[0 0 1 1]);
uistack(ha,'down')
II=imread('background.jpg');
image(II);
colormap gray
set(ha,'handlevisibility','off','visible','off');



movegui(game,'center');
matrix_board = zeros(n,n);
turn = 1;
game_over = false;

board_size = n;

%Music Setup
filename = 'FugueFat.mp3';
[y, Fs]= audioread(filename);
backgroundmusic = audioplayer(y,Fs);
if music == true
    play(backgroundmusic);
elseif music == false;
    stop(backgroundmusic);
end

%Button Generation
reset = uicontrol(game,'Style','pushbutton','Units','centimeters',...
'Position',[14,10,4,2],'FontSize',15,'Callback', @Reset,'String',...
'Reset', 'BackgroundColor','white','ForegroundColor','black');
settings = uicontrol(game,'Style','pushbutton','Units','centimeters',...
'Position',[14,3,4,2],'FontSize',15,'Callback', @Information,... 
'String','Settings', 'BackgroundColor','white','ForegroundColor','black');

%Creates the 3x3 board
if n == 3
    %Column 1
    sq11 = uicontrol(game,'Style','pushbutton','Units','centimeters',...
    'Position',[2,9,3,3],'FontSize',40,'Callback', @Move,... 
    'BackgroundColor','white','ForegroundColor','black','Tag','1');
    sq21 = uicontrol(game,'Style','pushbutton','Units','centimeters',...
    'Position',[2,6,3,3],'FontSize',40,'Callback', @Move,... 
    'BackgroundColor','white','ForegroundColor','black','Tag','2');
    sq31 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
    ,'Position',[2,3,3,3],'FontSize',40,'Callback', @Move,... 
    'BackgroundColor','white','ForegroundColor','black','Tag','3');
    %Column 2
    sq12 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
    ,'Position',[5,9,3,3],'FontSize',40,'Callback', @Move,... 
    'BackgroundColor','white','ForegroundColor','black','Tag','4');
    sq22 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
    ,'Position',[5,6,3,3],'FontSize',40,'Callback', @Move,... 
    'BackgroundColor','white','ForegroundColor','black','Tag','5');
    sq32 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
    ,'Position',[5,3,3,3],'FontSize',40,'Callback', @Move,... 
    'BackgroundColor','white','ForegroundColor','black','Tag','6');
    %Column 3
    sq13 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
    ,'Position',[8,9,3,3],'FontSize',40,'Callback', @Move,...
    'BackgroundColor','white','ForegroundColor','black','Tag','7');
    sq23 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
    ,'Position',[8,6,3,3],'FontSize',40,'Callback', @Move,... 
    'BackgroundColor','white','ForegroundColor','black','Tag','8');
    sq33 = uicontrol(game,'Style','pushbutton','Units','centimeters',...
    'Position',[8,3,3,3],'FontSize',40,'Callback', @Move,... 
    'BackgroundColor','white','ForegroundColor','black','Tag','9');
    return;
end
%Creates the 4x4 Board
if n == 4
    %Column 1
    sq11 = uicontrol(game,'Style','pushbutton','Units','centimeters',...
        'Position',[2,10,2.5,2.5],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','1');
    sq21 = uicontrol(game,'Style','pushbutton','Units','centimeters',...
        'Position',[2,7.5,2.5,2.5],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','2');
    sq31 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[2,5,2.5,2.5],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','3');
    sq41 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[2,2.5,2.5,2.5],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','4');
    %Column 2 
    sq12 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[4.5,10,2.5,2.5],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','5');
    sq22 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[4.5,7.5,2.5,2.5],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','6');
    sq32 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[4.5,5,2.5,2.5],'FontSize',40,'Callback', @Move,...
        'BackgroundColor','white','ForegroundColor','black','Tag','7');
    sq42 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[4.5,2.5,2.5,2.5],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','8');
    %Column 3
    sq13 = uicontrol(game,'Style','pushbutton','Units','centimeters',...
        'Position',[7,10,2.5,2.5],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','9');
    sq23 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[7,7.5,2.5,2.5],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','10');
    sq33 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[7,5,2.5,2.5],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','11');
    sq43 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[7,2.5,2.5,2.5],'FontSize',40,'Callback', @Move,...
        'BackgroundColor','white','ForegroundColor','black','Tag','12');
    %Column 4
    sq14 = uicontrol(game,'Style','pushbutton','Units','centimeters',...
        'Position',[9.5,10,2.5,2.5],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','13');
    sq24 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[9.5,7.5,2.5,2.5],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','14');
    sq34 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[9.5,5,2.5,2.5],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','15');
    sq44 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[9.5,2.5,2.5,2.5],'FontSize',40,'Callback', @Move,...
        'BackgroundColor','white','ForegroundColor','black','Tag','16');
    return;
end
%Creates the 5x5 board
if n == 5
    %Column 1
    sq11 = uicontrol(game,'Style','pushbutton','Units','centimeters',...
        'Position',[2,10,2,2],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','1');
    sq21 = uicontrol(game,'Style','pushbutton','Units','centimeters',...
        'Position',[2,8,2,2],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','2');
    sq31 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[2,6,2,2],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','3');
    sq41 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[2,4,2,2],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','4');
    sq51 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[2,2,2,2],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','5');
    %Column 2 
    sq12 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[4,10,2,2],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','6');
    sq22 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[4,8,2,2],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','7');
    sq32 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[4,6,2,2],'FontSize',40,'Callback', @Move,...
        'BackgroundColor','white','ForegroundColor','black','Tag','8');
    sq42 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[4,4,2,2],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','9');
    sq52 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
       ,'Position',[4,2,2,2],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','10');
    %Column 3
    sq13 = uicontrol(game,'Style','pushbutton','Units','centimeters',...
        'Position',[6,10,2,2],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','11');
    sq23 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[6,8,2,2],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','12');
    sq33 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[6,6,2,2],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','13');
    sq43 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[6,4,2,2],'FontSize',40,'Callback', @Move,...
        'BackgroundColor','white','ForegroundColor','black','Tag','14');
    sq53 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[6,2,2,2],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','15');
    %Column 4
    sq14 = uicontrol(game,'Style','pushbutton','Units','centimeters',...
        'Position',[8,10,2,2],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','16');
    sq24 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[8,8,2,2],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','17');
    sq34 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[8,6,2,2],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','18');
    sq44 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[8,4,2,2],'FontSize',40,'Callback', @Move,...
        'BackgroundColor','white','ForegroundColor','black','Tag','19');
    sq54 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[8,2,2,2],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','20');
    %Column 5
    sq15 = uicontrol(game,'Style','pushbutton','Units','centimeters',...
        'Position',[10,10,2,2],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','21');
    sq25 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[10,8,2,2],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','22');
    sq35 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[10,6,2,2],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','23');
    sq45 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[10,4,2,2],'FontSize',40,'Callback', @Move,...
        'BackgroundColor','white','ForegroundColor','black','Tag','24');
    sq55 = uicontrol(game,'Style','pushbutton','Units','centimeters'...
        ,'Position',[10,2,2,2],'FontSize',40,'Callback', @Move,... 
        'BackgroundColor','white','ForegroundColor','black','Tag','25');
    return;
end
end